---
abstract: '(Base) class for creating Riap::Simple server over pipe'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
  Perinci::Access::Simple::Client: 0.05
  Perinci::Examples: 0.10
  Test::More: 0.96
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perinci-Access-Simple-Server
requires:
  Class::XSAccessor: 0
  Data::Clean::JSON: 0
  File::HomeDir: 0
  IO::Handle::Record: 0
  JSON: 0
  Log::Any: 0
  Log::Any::App: 0
  Moo: 0
  Perinci::Access: 0
  Perinci::Gen::ForModule: 0
  Perinci::Sub::Wrapper: 0.23
  Perinci::Sub::property::timeout: 0
  Riap: 1.1.14
  SHARYANTO::Proc::Daemon::Prefork: 0.05
  URI::Escape: 0
  perl: 5.010000
resources:
  homepage: http://metacpan.org/release/Perinci-Access-Simple-Server
  repository: http://github.com/sharyanto/perl-Perinci-Access-Simple-Server
version: 0.08
