---
abstract: 'Riap::Simple server implementations'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Capture::Tiny: 0
  Module::Build: 0.3601
  Perinci::Access::Simple::Client: 0.05
  Perinci::Examples: 0.10
  Test::More: 0.96
  Test::Script: 1.05
  blib: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perinci-Access-Simple-Server
requires:
  Class::XSAccessor: 0
  Data::Clean::JSON: 0
  File::HomeDir: 0
  IO::Handle::Record: 0
  JSON: 0
  Log::Any: 0
  Log::Any::App: 0
  Module::List: 0
  Moo: 0
  Perinci::Access: 0
  Perinci::Access::Perl: 0
  Perinci::Access::Schemeless: 0
  Perinci::CmdLine: 0
  Perinci::Gen::ForModule: 0
  Riap: v1.1.14
  SHARYANTO::Proc::Daemon::Prefork: 0.05
  URI::Escape: 0
  perl: 5.010001
resources:
  homepage: http://metacpan.org/release/Perinci-Access-Simple-Server
  repository: http://github.com/sharyanto/perl-Perinci-Access-Simple-Server
version: 0.13
